name: Build and Push ThingsBoard Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build ThingsBoard and Docker Image
      run: |
        mvn clean install -DskipTests -Ddockerfile.skip=false -Dlicense.skip=true

    - name: Extract ThingsBoard version
      id: extract_version
      run: |
        echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: List Docker images
      run: docker images

    - name: Tag and push built Docker image
      run: |
        docker tag thingsboard/tb:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/tb:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/tb:latest
